---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-gateway
  labels:
    networking.knative.dev/ingress-provider: net-gateway-api
    app.kubernetes.io/component: net-gateway-api
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: devel
data:
  _example: |
    ################################
    #                              #
    #    EXAMPLE CONFIGURATION     #
    #                              #
    ################################

    # This block is not actually functional configuration,
    # but serves to illustrate the available configuration
    # options and document them in a way that is accessible
    # to users that `kubectl edit` this config map.
    #
    # These sample configuration options may be copied out of
    # this example block and unindented to be in the data block
    # to actually change the configuration.

    # When configuring Gateways below if 'service' is not provided,
    # net-gateway-api will use the first address on the Gateway status
    # for probing. This is useful when the Gateway proxy is off cluster.
    #
    # See: https://github.com/knative-extensions/net-gateway-api/issues/665

    # external-gateways defines the Gateway to be used for external traffic
    external-gateways: |
      - class: istio
        gateway: istio-system/knative-gateway
        service: istio-system/istio-ingressgateway
        supported-features:
        - HTTPRouteRequestTimeout

    # local-gateways defines the Gateway to be used for cluster local traffic
    local-gateways: |
      - class: istio
        gateway: istio-system/knative-local-gateway
        service: istio-system/knative-local-gateway
        supported-features:
        - HTTPRouteRequestTimeout
