---
apiVersion: v1
kind: Secret
metadata:
  name: net-gateway-api-webhook-certs
  labels:
    app.kubernetes.io/component: net-gateway-api
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: devel
    networking.knative.dev/ingress-provider: gateway-api
