---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: tcp
  namespace: kube-system
spec:
  gatewayClassName: cilium
  listeners:
    - name: tcp
      port: 80
      protocol: TCP
      allowedRoutes:
        kinds:
          - kind: TCPRoute
        namespaces:
          from: All
