---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: tls
  namespace: kube-system
spec:
  gatewayClassName: cilium
  listeners:
    - name: tls
      port: 443
      protocol: TLS
      allowedRoutes:
        kinds:
          - kind: TLSRoute
        namespaces:
          from: All
      tls:
        mode: Passthrough
