[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "minigrep"
path = "src/main.rs"

[lib]
name = "minigrep"
path = "src/lib.rs"

[dependencies]
rand = "0.8.5"
