[workspace.lints.rust]
#unsafe_code = "forbid"
unused = "allow"       # debug: For experimental dev.

[workspace]
resolver = "2"
members = [
  "pkg/libui",
  "pkg/libutil",
  "pkg/sandbox",
  "pkg/sandbox-macros",
  "pkg/sandbox-redis",
]
