[workspace.lints.rust]
unsafe_code = "forbid"
unused = "allow"       # debug: For experimental dev.

[workspace]
resolver = "2"
members = [
  "cmd/exercises",
  "cmd/guessing-game",
  "cmd/jarvis",
  "cmd/minigrep",
  "lib/lib-ai",
  "lib/lib-minigrep",
  "lib/lib-util",
  "lib/minion",
]
