[workspace.lints.rust]
#unsafe_code = "forbid"
unused = "allow"       # debug: For experimental dev.

[workspace]
resolver = "2"
members = [
  "hack/macros",
  "hack/sandbox",
  "lib/libui",
  "lib/libutil",
]
