[workspace.lints.rust]
unsafe_code = "forbid"
unused = "allow" # note: For experimental dev.

[workspace]
members = [
    # -- Libraries
    "lib/lib-exercise",
    "lib/lib-minigrep",
    # -- Commands
    "cmd/exercise-1",
    "cmd/guessing-game",
    "cmd/minigrep",
]
