// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: v1/hello.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - api.v1.Greeter

/// Namespace containing generated types for the "api.v1.Greeter" service.
public enum Api_V1_Greeter {
    /// Service descriptor for the "api.v1.Greeter" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "api.v1.Greeter")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "SayHello" metadata.
        public enum SayHello {
            /// Request type for "SayHello".
            public typealias Input = Api_V1_HelloRequest
            /// Response type for "SayHello".
            public typealias Output = Api_V1_HelloReply
            /// Descriptor for "SayHello".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "api.v1.Greeter"),
                method: "SayHello"
            )
        }
        /// Descriptors for all methods in the "api.v1.Greeter" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            SayHello.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "api.v1.Greeter" service.
    public static let api_v1_Greeter = GRPCCore.ServiceDescriptor(fullyQualifiedService: "api.v1.Greeter")
}

// MARK: api.v1.Greeter (server)

extension Api_V1_Greeter {
    /// Streaming variant of the service protocol for the "api.v1.Greeter" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Here is the overall greeting service definition where we define all our endpoints
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "SayHello" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Sends a greeting
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Api_V1_HelloRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Api_V1_HelloReply` messages.
        func sayHello(
            request: GRPCCore.StreamingServerRequest<Api_V1_HelloRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Api_V1_HelloReply>
    }

    /// Service protocol for the "api.v1.Greeter" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Here is the overall greeting service definition where we define all our endpoints
    public protocol ServiceProtocol: Api_V1_Greeter.StreamingServiceProtocol {
        /// Handle the "SayHello" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Sends a greeting
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Api_V1_HelloRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Api_V1_HelloReply` message.
        func sayHello(
            request: GRPCCore.ServerRequest<Api_V1_HelloRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Api_V1_HelloReply>
    }

    /// Simple service protocol for the "api.v1.Greeter" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Here is the overall greeting service definition where we define all our endpoints
    public protocol SimpleServiceProtocol: Api_V1_Greeter.ServiceProtocol {
        /// Handle the "SayHello" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Sends a greeting
        ///
        /// - Parameters:
        ///   - request: A `Api_V1_HelloRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Api_V1_HelloReply` to respond with.
        func sayHello(
            request: Api_V1_HelloRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Api_V1_HelloReply
    }
}

// Default implementation of 'registerMethods(with:)'.
extension Api_V1_Greeter.StreamingServiceProtocol {
    public func registerMethods(with router: inout GRPCCore.RPCRouter) {
        router.registerHandler(
            forMethod: Api_V1_Greeter.Method.SayHello.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Api_V1_HelloRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Api_V1_HelloReply>(),
            handler: { request, context in
                try await self.sayHello(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
extension Api_V1_Greeter.ServiceProtocol {
    public func sayHello(
        request: GRPCCore.StreamingServerRequest<Api_V1_HelloRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Api_V1_HelloReply> {
        let response = try await self.sayHello(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
extension Api_V1_Greeter.SimpleServiceProtocol {
    public func sayHello(
        request: GRPCCore.ServerRequest<Api_V1_HelloRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Api_V1_HelloReply> {
        return GRPCCore.ServerResponse<Api_V1_HelloReply>(
            message: try await self.sayHello(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: api.v1.Greeter (client)

extension Api_V1_Greeter {
    /// Generated client protocol for the "api.v1.Greeter" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Here is the overall greeting service definition where we define all our endpoints
    public protocol ClientProtocol: Sendable {
        /// Call the "SayHello" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Sends a greeting
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Api_V1_HelloRequest` message.
        ///   - serializer: A serializer for `Api_V1_HelloRequest` messages.
        ///   - deserializer: A deserializer for `Api_V1_HelloReply` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func sayHello<Result>(
            request: GRPCCore.ClientRequest<Api_V1_HelloRequest>,
            serializer: some GRPCCore.MessageSerializer<Api_V1_HelloRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Api_V1_HelloReply>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Api_V1_HelloReply>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "api.v1.Greeter" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Here is the overall greeting service definition where we define all our endpoints
    public struct Client: ClientProtocol {
        private let client: GRPCCore.GRPCClient

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient) {
            self.client = client
        }

        /// Call the "SayHello" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Sends a greeting
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Api_V1_HelloRequest` message.
        ///   - serializer: A serializer for `Api_V1_HelloRequest` messages.
        ///   - deserializer: A deserializer for `Api_V1_HelloReply` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func sayHello<Result>(
            request: GRPCCore.ClientRequest<Api_V1_HelloRequest>,
            serializer: some GRPCCore.MessageSerializer<Api_V1_HelloRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Api_V1_HelloReply>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Api_V1_HelloReply>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Api_V1_Greeter.Method.SayHello.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension Api_V1_Greeter.ClientProtocol {
    /// Call the "SayHello" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Sends a greeting
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Api_V1_HelloRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func sayHello<Result>(
        request: GRPCCore.ClientRequest<Api_V1_HelloRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Api_V1_HelloReply>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.sayHello(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Api_V1_HelloRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Api_V1_HelloReply>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension Api_V1_Greeter.ClientProtocol {
    /// Call the "SayHello" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Sends a greeting
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func sayHello<Result>(
        _ message: Api_V1_HelloRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Api_V1_HelloReply>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Api_V1_HelloRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.sayHello(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}