---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knative
resources:
  # note: spec.source.rabbitmq.enabled=true failing
  - https://github.com/knative-extensions/eventing-rabbitmq/releases/download/knative-v1.16.0/rabbitmq-source.yaml
  - source.yaml
