---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventmesh-backend
  labels:
    app.kubernetes.io/version: "v1.16.0"
    app.kubernetes.io/component: eventmesh-backend
rules:
  - apiGroups:
      - ""
    resources:
      # for config-logging and config-leader-election
      - configmaps
    verbs:
      - get
      - list
      - watch
  # permissions for leader election
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
