build:
  repo: []
  # - name: ""
  #   secret: ""
  #   url: ""
  #   username: ""
  container: []
  # - name: ""
  #   path: ""
  #   platform: ""
  #   files: []
  chart: []
  # - name: ""
  #   path: ""
  config: []
  # - name: ""
  #   value: ""
  runner: []
  # - name: ""
  #   config: ""
controller:
  - embedded: {}
  - subsystem:
      controller: {}
cloud:
  openstack: []
  vsphere: []
  ssh: []
cluster:
  kubernetes:
    capi: {}
    k0s: {}
    kubeadm: {}
core:
  kvirt: {} # harbor,cruiser
  osh: {} # ctl->ksvc
drot:
  primary: {}
  secondary:
    prime: {}
    lastknonwnprimary: {}
    lastknownprime: {}
    secondary: []
exec:
  loader: {} # prerun
  runner: {} # postrun
firmware:
  cloader: {}
hardware:
  cdev:
    fw: {}
    gw: {}
    hv: []
  cunit: # cap unit
    - type: amd64
    - type: arm64
    - type: riscv64
kernel:
  linux: [] # vm
  lm4: {} # hv
os:
  - # fw
    name: panos
    type: firewall
  - # gw
    name: vyos
    type: gateway
  - # svc
    name: ubuntu
    type: service
  - # mgmt
    name: macos
    type: management
    client:
      tool: []
  - # client
    name: ios
    type: client
  - # client
    name: watchos
    type: client
  - # client
    name: tvos
    type: client
osh:
  harbor:
    keystone: {}
  cruiser:
    ctl:
      glance: {}
      horizon: {}
      swift: {}
      designate: {}
    cli:
      cinder: {}
      nova: {}
      neutron: {}
      octavia: {}
pkg: []
# - bin:c
# - app:h
ref: []
# - name: ""
#   description: ""
#   url: ""
server:
  knative: {}
  service: []
service:
  cruiser: []
  harbour: {}
  hello: {}
shell:
  clos: {}
source:
  git: []
  archive: []
status:
  - server: {} # stateless
  - client: {} # statefull
uri:
  certified: []
  community: []
  origin: {}
  rot: {}
  sandbox: {}
version:
  "-1": null
  "-2": null
  main: {}
  stable: {}
  lts: {}
  archived: []
  discarded: []
