[package]
name = "oscore"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
spin = "0.9.8"
volatile = "0.2.6"

[lints.rust]
unsafe_code = "allow"
