---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: headlamp
  namespace: headlamp
spec:
  hostnames:
    - dashboard.kube.local
  rules:
    - backendRefs:
        - name: headlamp
          port: 80
  parentRefs:
    - name: default
      namespace: kube-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: registry
  namespace: kube-system
spec:
  hostnames:
    - registry.kube.local
  rules:
    - backendRefs:
        - name: registry
          port: 80
  parentRefs:
    - name: default
      namespace: kube-system
