---
apiVersion: v1
kind: Pod
metadata:
  name: hellodev
  namespace: sandbox
  annotations:
    checkov.io/skip1: CKV2_K8S_6=Not caring about Network Policies for now
spec:
  automountServiceAccountToken: false
  restartPolicy: Always
  runtimeClassName: gvisor
  securityContext:
    runAsNonRoot: true
    runAsUser: 65536
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: docker
      image: docker@sha256:d88116ec7a4eb0cec95848a61b46920f2d9d7198023b72da1b0848e853a5e12a # docker:27.3.1-dind-rootless
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
            - NET_RAW
      args:
        - /bin/bash
        - -c
        - touch /tmp/healthy; sleep 3600
      resources:
        limits:
          memory: 128Mi
          cpu: 500m
        requests:
          memory: 64Mi
          cpu: 250m
      livenessProbe:
        initialDelaySeconds: 5
        periodSeconds: 5
        exec:
          command:
            - cat
            - /tmp/healthy
      readinessProbe:
        initialDelaySeconds: 5
        periodSeconds: 5
        exec:
          command:
            - docker
            - version
