---
apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: sandbox
spec:
  api:
    sans:
      - kube.sand.dev.local
  network:
    provider: custom
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
  featureGates:
    - name: UserNamespacesSupport
      enabled: true
  extensions:
    helm:
      charts:
        - name: cilium
          chartname: cilium/cilium
          namespace: kube-system
          order: 1
          version: 1.14.3
          values: |
            externalIPs:
              enabled: true
            hostFirewall:
              enabled: true
            loadBalancer:
              algorithm: maglev
              l7:
                backend: envoy
              mode: dsr
              serviceTopology: true
            monitor:
              enabled: true
            operator:
              replicas: 1
            tunnel: disabled
        - name: openebs
          chartname: openebs/openebs
          namespace: kube-system
          order: 2
          version: 3.9.0
          values: |
            analytics:
              enabled: false
            localprovisioner:
              deviceClass:
                enabled: false
              hostpathClass:
                isDefaultClass: true
            ndm:
              enabled: false
        - name: flux
          chartname: bitnami/flux
          namespace: cicd
          order: 3
          version: 1.1.1
          values: |
            global:
              storageClass: openebs-hostpath
              persistence:
                enabled: true
      repositories:
        - name: bitnami
          url: https://charts.bitnami.com/bitnami/
        - name: cilium
          url: https://helm.cilium.io/
        - name: openebs
          url: https://openebs.github.io/charts/
  telemetry:
    enabled: false
