---
apiVersion: kind.x-k8s.io/v1alpha1
kind: Cluster
networking:
  apiServerAddress: 127.0.0.1
  apiServerPort: 6443
  disableDefaultCNI: false
featureGates:
  UserNamespacesSupport: true
nodes:
  - role: control-plane
    #extraMounts:
    #  - hostPath: /var/run/docker.sock
    #    containerPath: /var/run/docker.sock
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
        listenAddress: 0.0.0.0
      - containerPort: 443
        hostPort: 443
        protocol: TCP
        listenAddress: 0.0.0.0
      - containerPort: 31443
        hostPort: 31443
        protocol: TCP
        listenAddress: 0.0.0.0
