binary:
  - name: helm
    enabled: true
    path: ${os}-${arch}/helm
    type: archive
    url: https://get.helm.sh/helm-v${version}-${os}-${arch}.tar.gz
    version: 3.17.0
    archs:
      - amd64
      - arm64
  - name: kustomize
    enabled: true
    path: ""
    type: archive
    url: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v${version}/kustomize_v${version}_${os}_${arch}.tar.gz
    version: 5.6.0
    archs:
      - amd64
      - arm64
  - name: krew
    url: https://github.com/kubernetes-sigs/krew/releases/download/v${version}/krew-${os}_${arch}.tar.gz
    enabled: true
    path: krew-${os}_${arch}
    pre: sudo mkdir -p /usr/local/krew && sudo chmod -R 777 /usr/local/krew
    post: install krew
    type: archive
    version: 0.4.4
    workspace: /usr/local/krew
    archs:
      - amd64
      - arm64
  - name: kubectl
    enabled: true
    type: executable
    url: https://dl.k8s.io/release/v${version}/bin/${os}/${arch}/kubectl
    version: 1.32.1
    archs:
      - amd64
      - arm64
  - name: k0sctl
    enabled: true
    type: executable
    url: https://github.com/k0sproject/k0sctl/releases/download/v${version}/k0sctl-${os}-${arch}
    version: 0.22.0
    archs:
      - amd64
      - arm64
  - name: cfssl
    enabled: true
    type: executable
    url: https://github.com/cloudflare/cfssl/releases/download/v${version}/cfssl_${version}_${os}_${arch}
    version: 1.6.5
    archs:
      - amd64
      - arm64
  - name: cfssljson
    enabled: true
    type: executable
    url: https://github.com/cloudflare/cfssl/releases/download/v${version}/cfssljson_${version}_${os}_${arch}
    version: 1.6.5
    archs:
      - amd64
      - arm64
package:
  add: []
  # - name: ""
  #   enabled: true
  #   keyring: ""
  #   repo: ""
  #   type: apt
  remove: []
  # - name: containerd
  #   enabled: true
  #   type: apt
  group:
    - name: default
      enabled: true
      type: apt
      add:
        - bash
        - ca-certificates
        - conntrack
        - cron
        - file
        - iproute2
        - kmod
        - libseccomp2
        - mount
        - nftables
        - open-iscsi
        - openssl
        - pigz
        - procps
        - software-properties-common
        - ssh
        - udev
        - util-linux
    - name: docker
      enabled: true
      keyring: https://download.docker.com/${os}/ubuntu/gpg
      repo: https://download.docker.com/${os}/ubuntu
      type: apt
      add:
        - containerd.io
        - docker-buildx-plugin
        - docker-ce-cli
        - docker-ce
        - docker-compose-plugin
      remove:
        - containerd
        - docker-compose
        - docker-doc
        - docker.io
        # - podman-docker
        - runc
    - name: toolchain
      enabled: true
      type: apt
      add:
        - avahi-utils
        - binutils
        - bison
        - build-essential
        - ccache
        - clang
        - cmake
        - default-jre
        - dfu-util
        - flex
        - g++
        - gcc
        - git
        - gnupg2
        - gperf
        - libavahi-client-dev
        - libc6-dev
        - libcairo2-dev
        - libcurl4
        - libdbus-1-dev
        - libedit2
        - libelf-dev
        - libffi-dev
        - libgcc-9-dev
        - libgirepository1.0-dev
        - libglib2.0-dev
        - libncurses6
        - libreadline-dev
        - libsdl2-dev
        - libsqlite3-0
        - libssl-dev
        - libssl-dev
        - libstdc++-9-dev
        - libusb-1.0-0
        - libxml2
        - libz3-dev
        - lld
        - llvm
        - ninja-build
        - pipx
        - pkg-config
        - python3
        - python3-dev
        - python3-pip
        - python3-venv
        # - repo
        - tzdata
        - unzip
        - uuid-dev
        - wget
        - wine
        - wine64
        - zlib1g-dev
plugin:
  - name: kubectl
    enabled: true
    installer: krew
    list:
      - access-matrix
      - ca-cert
      - cert-manager
      - cilium
      - config-import
      - ctx
      - debug-shell
      - deprecations
      - df-pv
      - hns
      - images
      - minio
      - node-shell
      - ns
      - nsenter
      - oidc-login
      - open-svc
      - openebs
      - pod-shell
      - rabbitmq
      - rook-ceph
      - view-cert
      - view-secret
      - view-utilization
      - view-webhook
      - virt
