[package]
name = "sandbox-redis"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"

[[bin]]
name = "client"

[dependencies]
bytes = "1"
mini-redis = "0.4"
tokio = { version = "1", features = ["full"] }

[lints]
workspace = true
