[package]
name = "advance"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "unsafe"
path = "src/unsafe.rs"

[[bin]]
name = "traits"
path = "src/traits.rs"

[[bin]]
name = "types"
path = "src/types.rs"

[dependencies]

[lints]
workspace = true
