version: '3'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:dev-ubuntu
    init: true
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    entrypoint:
      - sleep
      - infinity
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ..
        target: /workspace
    env_file:
      - ../.env
