#!/bin/bash
# SPDX-License-Identifier: GPL-3.0

set -eo pipefail

: "${CPUS:=4}"
: "${DISK_SIZE:="64GiB"}"
: "${MEMORY:="16GiB"}"
: "${PSP:="config/psp.yaml"}"
: "${RBAC:="config/rbac.yaml"}"

# note:
# - minikube starts services that may be available on the Internet. Please ensure that you have a firewall to protect your host from unexpected access. For instance:
# - apiserver listens on TCP *:8443
# - kubelet listens on TCP *:10250 and *:10255
# - kube-scheduler listens on TCP *:10259
# - kube-controller listens on TCP *:10257

# debug: Run minikube start --alsologtostderr -v=4 to debug crashes

# issues:
# - https://github.com/kubernetes/minikube/labels/co%2Fkvm2-driver
# - https://github.com/kubernetes/minikube/labels/co%2Fnone-driver
# - https://github.com/kubernetes/minikube/labels/co%2Fvfkit

# ref:
# - https://minikube.sigs.k8s.io/docs/drivers/none/

# todo: minikube vm
if grep -E -q 'vmx|svm' /proc/cpuinfo >/dev/null 2>&1; then
  export DRIVER="kvm2"
  export OPT="--profile=kubevirt --kvm-gpu=false --hidden=true --kvm-network='' --network='' --kvm-qemu-uri=qemu:///system"
else
  export DRIVER="vfkit"
fi

# note: minikube cluster
sudo minikube config set cpus "${CPUS}"
sudo minikube config set disk-size "${DISK_SIZE}"
sudo minikube config set driver "${DRIVER}"
sudo minikube config set memory "${MEMORY}"
minikube start \
  --addons=pod-security-policy \
  --container-runtime=containerd \
  --docker-opt=containerd=/var/run/containerd/containerd.sock \
  --driver="${DRIVER}" \
  --extra-config=apiserver.enable-admission-plugins=PodSecurityPolicy
kubectl apply -f "${RBAC}"
kubectl apply -f "${PSP}"

# note: addons
# todo: custom images
# fixme: gadget
# minikube addons enable inspektor-gadget
# gvisor
minikube addons enable gvisor
# headlamp
minikube addons enable headlamp
kubectl -n headlamp create token headlamp
minikube addons enable metrics-server
# fixme: repo
# minikube addons enable registry
# minikube addons enable registry-aliases
# snapshots
minikube addons enable volumesnapshots

# todo: kvirt
if grep -E -q 'vmx|svm' /proc/cpuinfo >/dev/null 2>&1; then
  minikube config -p kubevirt set memory "${MEMORY}"
  minikube start -p kubevirt
fi

# todo: minikube tunnel
# todo: cmd <start|delete>
