[package]
name = "grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
api = { path = "../api" }
prost = "0.13.1"
tokio = { version = "1.39.3", features = ["rt-multi-thread"] }
tonic = "0.12.1"

[lints]
workspace = true
