name: Hello World

on:
  - push

jobs:
  hello:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
<<<<<<< HEAD
      - uses: ../../build/actions/checkout@v3
      - id: foo
        uses: actions/hello@sandbox
=======
      - uses: actions/checkout@v3
      - id: foo
        uses: ./build/actions/hello
>>>>>>> 5210778 (Demo actions (#41))
        with:
          who-to-greet: Mona the Octocat
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
