name: hello

on:
  - workflow_dispatch

jobs:
  hello:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./build/actions/hello
        with:
          who-to-greet: Mona the Octocat
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
